/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthInitPwdIndexRouteImport } from './routes/auth/init-pwd/index'
import { Route as AuthForgetPwdIndexRouteImport } from './routes/auth/forget-pwd/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInitPwdIndexRoute = AuthInitPwdIndexRouteImport.update({
  id: '/init-pwd/',
  path: '/init-pwd/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPwdIndexRoute = AuthForgetPwdIndexRouteImport.update({
  id: '/forget-pwd/',
  path: '/forget-pwd/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forget-pwd/': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd/': typeof AuthInitPwdIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forget-pwd': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd': typeof AuthInitPwdIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forget-pwd/': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd/': typeof AuthInitPwdIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/forget-pwd/'
    | '/auth/init-pwd/'
    | '/auth/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/auth/forget-pwd' | '/auth/init-pwd' | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/forget-pwd/'
    | '/auth/init-pwd/'
    | '/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/init-pwd/': {
      id: '/auth/init-pwd/'
      path: '/init-pwd'
      fullPath: '/auth/init-pwd/'
      preLoaderRoute: typeof AuthInitPwdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forget-pwd/': {
      id: '/auth/forget-pwd/'
      path: '/forget-pwd'
      fullPath: '/auth/forget-pwd/'
      preLoaderRoute: typeof AuthForgetPwdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgetPwdIndexRoute: typeof AuthForgetPwdIndexRoute
  AuthInitPwdIndexRoute: typeof AuthInitPwdIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetPwdIndexRoute: AuthForgetPwdIndexRoute,
  AuthInitPwdIndexRoute: AuthInitPwdIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
