/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthInitPwdIndexRouteImport } from './routes/auth/init-pwd/index'
import { Route as AuthForgetPwdIndexRouteImport } from './routes/auth/forget-pwd/index'
import { Route as appScolariteIndexRouteImport } from './routes/(app)/scolarite/index'
import { Route as appPlanningIndexRouteImport } from './routes/(app)/planning/index'
import { Route as appAdminAccountsIndexRouteImport } from './routes/(app)/admin/accounts/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInitPwdIndexRoute = AuthInitPwdIndexRouteImport.update({
  id: '/init-pwd/',
  path: '/init-pwd/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPwdIndexRoute = AuthForgetPwdIndexRouteImport.update({
  id: '/forget-pwd/',
  path: '/forget-pwd/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appScolariteIndexRoute = appScolariteIndexRouteImport.update({
  id: '/scolarite/',
  path: '/scolarite/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlanningIndexRoute = appPlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminAccountsIndexRoute = appAdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/planning/': typeof appPlanningIndexRoute
  '/scolarite/': typeof appScolariteIndexRoute
  '/auth/forget-pwd/': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd/': typeof AuthInitPwdIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/admin/accounts/': typeof appAdminAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/planning': typeof appPlanningIndexRoute
  '/scolarite': typeof appScolariteIndexRoute
  '/auth/forget-pwd': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd': typeof AuthInitPwdIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/admin/accounts': typeof appAdminAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(app)/planning/': typeof appPlanningIndexRoute
  '/(app)/scolarite/': typeof appScolariteIndexRoute
  '/auth/forget-pwd/': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd/': typeof AuthInitPwdIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/(app)/admin/accounts/': typeof appAdminAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planning/'
    | '/scolarite/'
    | '/auth/forget-pwd/'
    | '/auth/init-pwd/'
    | '/auth/login/'
    | '/admin/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planning'
    | '/scolarite'
    | '/auth/forget-pwd'
    | '/auth/init-pwd'
    | '/auth/login'
    | '/admin/accounts'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/auth'
    | '/(app)/planning/'
    | '/(app)/scolarite/'
    | '/auth/forget-pwd/'
    | '/auth/init-pwd/'
    | '/auth/login/'
    | '/(app)/admin/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/init-pwd/': {
      id: '/auth/init-pwd/'
      path: '/init-pwd'
      fullPath: '/auth/init-pwd/'
      preLoaderRoute: typeof AuthInitPwdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forget-pwd/': {
      id: '/auth/forget-pwd/'
      path: '/forget-pwd'
      fullPath: '/auth/forget-pwd/'
      preLoaderRoute: typeof AuthForgetPwdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/scolarite/': {
      id: '/(app)/scolarite/'
      path: '/scolarite'
      fullPath: '/scolarite/'
      preLoaderRoute: typeof appScolariteIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/planning/': {
      id: '/(app)/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof appPlanningIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin/accounts/': {
      id: '/(app)/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof appAdminAccountsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appPlanningIndexRoute: typeof appPlanningIndexRoute
  appScolariteIndexRoute: typeof appScolariteIndexRoute
  appAdminAccountsIndexRoute: typeof appAdminAccountsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appPlanningIndexRoute: appPlanningIndexRoute,
  appScolariteIndexRoute: appScolariteIndexRoute,
  appAdminAccountsIndexRoute: appAdminAccountsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgetPwdIndexRoute: typeof AuthForgetPwdIndexRoute
  AuthInitPwdIndexRoute: typeof AuthInitPwdIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetPwdIndexRoute: AuthForgetPwdIndexRoute,
  AuthInitPwdIndexRoute: AuthInitPwdIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
