/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthInitPwdIndexRouteImport } from './routes/auth/init-pwd/index'
import { Route as AuthForgetPwdIndexRouteImport } from './routes/auth/forget-pwd/index'
import { Route as appTeachersIndexRouteImport } from './routes/(app)/teachers/index'
import { Route as appPlanningIndexRouteImport } from './routes/(app)/planning/index'
<<<<<<< HEAD
import { Route as appBuildingsIndexRouteImport } from './routes/(app)/buildings/index'
import { Route as appBuildingsBuildingIdRouteImport } from './routes/(app)/buildings/$buildingId'
=======
import { Route as appGroupesIndexRouteImport } from './routes/(app)/groupes/index'
>>>>>>> develop

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInitPwdIndexRoute = AuthInitPwdIndexRouteImport.update({
  id: '/init-pwd/',
  path: '/init-pwd/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPwdIndexRoute = AuthForgetPwdIndexRouteImport.update({
  id: '/forget-pwd/',
  path: '/forget-pwd/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appTeachersIndexRoute = appTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlanningIndexRoute = appPlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => appRouteRoute,
} as any)
<<<<<<< HEAD
const appBuildingsIndexRoute = appBuildingsIndexRouteImport.update({
  id: '/buildings/',
  path: '/buildings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appBuildingsBuildingIdRoute = appBuildingsBuildingIdRouteImport.update({
  id: '/buildings/$buildingId',
  path: '/buildings/$buildingId',
=======
const appGroupesIndexRoute = appGroupesIndexRouteImport.update({
  id: '/groupes/',
  path: '/groupes/',
>>>>>>> develop
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
<<<<<<< HEAD
  '/buildings/$buildingId': typeof appBuildingsBuildingIdRoute
  '/buildings/': typeof appBuildingsIndexRoute
=======
  '/groupes/': typeof appGroupesIndexRoute
>>>>>>> develop
  '/planning/': typeof appPlanningIndexRoute
  '/teachers/': typeof appTeachersIndexRoute
  '/auth/forget-pwd/': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd/': typeof AuthInitPwdIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
<<<<<<< HEAD
  '/buildings/$buildingId': typeof appBuildingsBuildingIdRoute
  '/buildings': typeof appBuildingsIndexRoute
=======
  '/groupes': typeof appGroupesIndexRoute
>>>>>>> develop
  '/planning': typeof appPlanningIndexRoute
  '/teachers': typeof appTeachersIndexRoute
  '/auth/forget-pwd': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd': typeof AuthInitPwdIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
<<<<<<< HEAD
  '/(app)/buildings/$buildingId': typeof appBuildingsBuildingIdRoute
  '/(app)/buildings/': typeof appBuildingsIndexRoute
=======
  '/(app)/groupes/': typeof appGroupesIndexRoute
>>>>>>> develop
  '/(app)/planning/': typeof appPlanningIndexRoute
  '/(app)/teachers/': typeof appTeachersIndexRoute
  '/auth/forget-pwd/': typeof AuthForgetPwdIndexRoute
  '/auth/init-pwd/': typeof AuthInitPwdIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
<<<<<<< HEAD
    | '/buildings/$buildingId'
    | '/buildings/'
=======
    | '/groupes/'
>>>>>>> develop
    | '/planning/'
    | '/teachers/'
    | '/auth/forget-pwd/'
    | '/auth/init-pwd/'
    | '/auth/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
<<<<<<< HEAD
    | '/buildings/$buildingId'
    | '/buildings'
=======
    | '/groupes'
>>>>>>> develop
    | '/planning'
    | '/teachers'
    | '/auth/forget-pwd'
    | '/auth/init-pwd'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/auth'
<<<<<<< HEAD
    | '/(app)/buildings/$buildingId'
    | '/(app)/buildings/'
=======
    | '/(app)/groupes/'
>>>>>>> develop
    | '/(app)/planning/'
    | '/(app)/teachers/'
    | '/auth/forget-pwd/'
    | '/auth/init-pwd/'
    | '/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/init-pwd/': {
      id: '/auth/init-pwd/'
      path: '/init-pwd'
      fullPath: '/auth/init-pwd/'
      preLoaderRoute: typeof AuthInitPwdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forget-pwd/': {
      id: '/auth/forget-pwd/'
      path: '/forget-pwd'
      fullPath: '/auth/forget-pwd/'
      preLoaderRoute: typeof AuthForgetPwdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/teachers/': {
      id: '/(app)/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof appTeachersIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/planning/': {
      id: '/(app)/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof appPlanningIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
<<<<<<< HEAD
    '/(app)/buildings/': {
      id: '/(app)/buildings/'
      path: '/buildings'
      fullPath: '/buildings/'
      preLoaderRoute: typeof appBuildingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/buildings/$buildingId': {
      id: '/(app)/buildings/$buildingId'
      path: '/buildings/$buildingId'
      fullPath: '/buildings/$buildingId'
      preLoaderRoute: typeof appBuildingsBuildingIdRouteImport
=======
    '/(app)/groupes/': {
      id: '/(app)/groupes/'
      path: '/groupes'
      fullPath: '/groupes/'
      preLoaderRoute: typeof appGroupesIndexRouteImport
>>>>>>> develop
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
<<<<<<< HEAD
  appBuildingsBuildingIdRoute: typeof appBuildingsBuildingIdRoute
  appBuildingsIndexRoute: typeof appBuildingsIndexRoute
=======
  appGroupesIndexRoute: typeof appGroupesIndexRoute
>>>>>>> develop
  appPlanningIndexRoute: typeof appPlanningIndexRoute
  appTeachersIndexRoute: typeof appTeachersIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
<<<<<<< HEAD
  appBuildingsBuildingIdRoute: appBuildingsBuildingIdRoute,
  appBuildingsIndexRoute: appBuildingsIndexRoute,
=======
  appGroupesIndexRoute: appGroupesIndexRoute,
>>>>>>> develop
  appPlanningIndexRoute: appPlanningIndexRoute,
  appTeachersIndexRoute: appTeachersIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgetPwdIndexRoute: typeof AuthForgetPwdIndexRoute
  AuthInitPwdIndexRoute: typeof AuthInitPwdIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetPwdIndexRoute: AuthForgetPwdIndexRoute,
  AuthInitPwdIndexRoute: AuthInitPwdIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
